config/routes.rb
Miniblog::Application.routes.draw do
  get "articles/index"
  resources :users, only:[:new, :create]
  resources :articles, only: [:index, :show] do
    resource :comments
  end

  root 'articles#index'
  get '/about' => 'static#about'
  get '/search' => 'search#results'

  get '/login' => 'session#new'

  post '/login' => 'session#create'
  delete "/logout" => "session#logout"

  namespace :admin do
      get "/" => "dashboard#index"
      resources :articles

    end

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments
  
# this must be singular
  belongs_to :author
# belongs_to must have foreign key, add on migration file
  has_many :reviews

  validates :story, presence: true
  validates :heading, presence: true, uniqueness: true



end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :articles
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article

  validates :comment, presence: true



end

app/models/review.rb
class Review < ActiveRecord::Base

  belongs_to :article

  def self.average_rating
    average(:rating)
    
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password


end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < AdminController
  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to admin_articles_path, notice: "yaya"
    else
      flash[:alert] = "oops"
      render :new
    end
  end
  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update_attributes(article_params)
      redirect_to admin_articles_path, notice: "yaya"
    else
      flash[:alert] = "oops"
      render :edit
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to admin_articles_path, notice: "no more"
    
    end
  
  private
  
  def article_params
    params.require(:article).permit(:heading, :story, :author)
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < AdminController



  def index
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  http_basic_authenticate_with name: "dave", password: "password"

  layout "admin"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    if session[:user_id].present?
      @current_user ||= User.find(session[:user_id])
    end

  end

  helper_method :current_user

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index

    @articles = Article.all.page(params[:page]).per(3)
  end

  # GET /articles/1s
  # GET /articles/1.json
  def show
    @comment = @article.comments.build
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render action: 'show', status: :created, location: @article }
      else
        format.html { render action: 'new' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:heading, :story, :publish_date, :author, :image)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :find_article

  def create
    @comment = @article.comments.build(comment_params)
    if @comment.save
      redirect_to(@article, notice: "yay")
    else
      flash[:alert] = "boo"
      render "articles/show"

      end
    
  end

  private

  def find_article
    @article = Article.find(params[:article_id])

  end

  def comment_params
    params.require(:comment).permit(:comment)
    
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def results
    @articles = Article.where(author: params[:author]).page(params[:page]).per(4)
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(email: params[:email])
    if user.authentication(params[:password])
      session[:current_user] 
      redirect_to root_path, notice: "Logged in!"

    else
      flash[:alert] = "Wrong info, dude"
      render :new
    end
  end

  def logout
    reset_session
    redirect_to(root_path, notice: "goodbye")
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  
  def new
    reset_session
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
    redirect_to root_path, notice: "Welcome"
    else 
      flash[:alert] = "oops"
      render :new
    end
  end

private 
  def user_params
    params.require(:user).permit(:name, :email, :age, :password, :password_confirmation)
      
  end
end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def star_jones(rating = 0)

    stars = ""
    rating.to_i.times do 
    stars += content_tag(:i, " ", class: "icon-star")
    
    end
    if rating > rating.floor
      stars += content_tag(:i, " ", class: "icon-star-half")
      end
    stars.html_safe


  end

  def logged_in?
    current_user.present?
  end


end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/admin/articles/edit.html.erb
<h1>edit</h2>


    <%= form_for([:admin, @article]) do |f| %>
  <div class="control-group">
    <%= f.label(:heading ) %>
    <%= f.text_field(:heading ) %>
  </div>
  <div class="control-group">
    <%= f.label(:story ) %>
    <%= f.text_field(:story ) %>
  </div>
  <div class="control-group">
    <%= f.label(:author_id) %>
    <%= f.select(:author_id, options_for_select(Author.all.collect {|a| [a.name, a.id]})) %> 
  </div>
  <div class="control-group">
    <%= f.submit("Submit") %>
  </div>
    <% end %>

app/views/admin/articles/index.html.erb
<%= link_to("New", new_admin_article_path) %>

<h1>Admin Index</h1>

<table class="table table-striped">
  <tbody>
    <% @articles.each do |article| %>
    <tr>
      <td><%= article.author %></td>
      <td><%= article.story %></td>
      <td><%= link_to "Edit Article", edit_admin_article_path(article) %></td>
      <td> <%= link_to "Delete", admin_article_path(article), method: :delete, confirm: "sure?" %></td>

    </tr>

s
    <% end %>
  </tbody>

  </table>

app/views/admin/articles/new.html.erb
<h1>new</h2>


    <%= form_for([:admin, @article]) do |f| %>
  <div class="control-group">
    <%= f.label(:heading ) %>
    <%= f.text_field(:heading) %>
  </div>
  <div class="control-group">
    <%= f.label(:story ) %>
    <%= f.text_field(:story) %>s
  </div>
  <div class="control-group">
    <%= f.label(:author_id) %>
    <%= f.select(:author_id, options_for_select(Author.all.collect {|a| [a.name, a.id]})) %> 
  </div>
  <div class="control-group">
    <%= f.submit("Submit") %>
  </div>
    <% end %>

app/views/articles/_form.html.erb
<%= form_for @article, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :heading, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :heading, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :story, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :story, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :publish_date, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :publish_date, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :author, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :author, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :image, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :image, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                articles_path, :class => 'btn' %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<%- model_class = Article -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/articles/index.html.erb
<%- model_class = Article -%>
<div class="page-header">
  <h1>Articles</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:heading) %></th>
      <th><%= model_class.human_attribute_name(:story) %></th>
      <th><%= model_class.human_attribute_name(:publish_date) %></th>
      <th><%= model_class.human_attribute_name(:author) %></th>
      <th><%= model_class.human_attribute_name(:image) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= link_to article.id, article_path(article) %></td>
        <td><%= article.heading %></td>
        <td><%= article.story %></td>
        <td><%= article.publish_date %></td>
        <td><%= link_to(article.author, search_path(author: article.author)) %></td>
        <td><%= article.image %></td>
        <td><%=l article.created_at %></td>
      

        
      </tr>
    <% end %>
  </tbody>
</table>
<div class="paging">
<%= paginate(@articles) %> </div>

app/views/articles/new.html.erb
<%- model_class = Article -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/articles/show.html.erb
<%- model_class = Article -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>
<p>

Reviews: <%= star_jones(@article.reviews.average_rating) %>
</p>



<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:heading) %>:</strong></dt>
  <dd><%= @article.heading %></dd>
  <dt><strong><%= model_class.human_attribute_name(:story) %>:</strong></dt>
  <dd><%= @article.story %></dd>
  <dt><strong><%= model_class.human_attribute_name(:publish_date) %>:</strong></dt>
  <dd><%= @article.publish_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:author) %>:</strong></dt>
  <dd><%= @article.author %></dd>
  <dt><strong><%= model_class.human_attribute_name(:image) %>:</strong></dt>
  <dd><%= @article.image %></dd>
</dl>

<% @article.comments.each do |comment| %>
<% next if comment.created_at.nil? %>
<div class="comment">
    <%= comment.comment %> - <em><%= time_ago_in_words(comment.created_at) %></em>
  </div>

  <% end %>


<div class="comment-form-box-thing">
    <%= form_for([@article, @comment]) do |f| %>
  <p>
    <%=f.label(:comment) %>
    <%=f.text_area(:comment) %>
  </p>
  <p>
    <%=f.submit('Whine and complain', class: 'btn btn-lg') %>
  </p>
   <% end %>
</div>
<div class="form-actions">
  
</div>